---
title: Interpreting and Visualizing GAMs
author: "Nick Giangreco"
output: html_document
---

```{r setup,message=F,warning=F}
knitr::opts_chunk$set(echo = TRUE,dpi = 400)
```

# Significance and linearity

```{r}

library(gamair)
data("mpg", package="gamair")

library(mgcv)
# Fit the model
mod_city4 <- gam(city.mpg ~ s(weight) + s(length) + s(price) + s(rpm) + s(width),
                 data = mpg, method = "REML")

# View the summary
summary(mod_city4)

```

# Plotting the motorcycle crash data and model

```{r}

mcycle <- MASS::mcycle

# Fit the model
mod <- gam(accel ~ s(times), data = mcycle, method = "REML")

# Make the plot with residuals
plot(mod,residuals=T)

# Change shape of residuals
plot(mod, residuals=T,pch=1,cex=1)

```

# Plotting multiple auto performance variables

```{r}

data("mpg", package="gamair")

# Fit the model
mod <- gam(hw.mpg ~ s(weight) + s(rpm) + s(price) + comp.ratio, 
           data = mpg, method = "REML")

# Plot the price effect
plot(mod,select=c(3))

# Plot all effects
plot(mod,pages=1,all.terms=T)

```

# Visualizing auto performance uncertainty

```{r}


# Fit the model
mod <- gam(hw.mpg ~ s(weight) + s(rpm) + s(price) + comp.ratio, 
           data = mpg, method = "REML")

# Plot the weight effect with colored shading
plot(mod, select = 1, shade=T, shade.col="hotpink")

# Make another plot adding the intercept value and uncertainty
plot(mod, select = 1, shift=coef(mod)[1])

```

# Reading model diagnostics

```{r}

set.seed(0)
dat <- gamSim(1,n=200)

library(mgcv)
# Fit the model
mod <- gam(y ~ s(x0, k = 5) + s(x1, k = 5) + s(x2, k = 5) + s(x3, k = 5),
           data = dat, method = "REML")

# Run the check function
gam.check(mod)

```

# Fixing problems with model diagnostics

```{r}

set.seed(0)
dat <- mgcv::gamSim(1,n=600, scale=0.6, verbose=FALSE)

# Fit the model
mod <- gam(y ~ s(x0, k = 3) + s(x1, k = 3) + s(x2, k = 3) + s(x3, k = 3),
           data = dat, method = "REML")

# Check the diagnostics
gam.check(mod)

# Refit to fix issues
mod2 <- gam(y ~ s(x0, k = 3) + s(x1, k = 3) + s(x2, k = 12) + s(x3, k = 3),
           data = dat, method = "REML")

# Check the new model
gam.check(mod2)

```

# Examining the overall concurivity in auuuto data

```{r}

set.seed(0)

# Fit the model
mod <- gam(hw.mpg ~ s(length) + s(width) + s(height) + s(weight),
           data = mpg, method = "REML")

# Check overall concurvity
concurvity(mod,full=T)

```

# Examining concurvity between auto variables

```{r}

# Fit the model
mod <- gam(hw.mpg ~ s(length) + s(width) + s(height) + s(weight),
           data = mpg, method = "REML")

# Check pairwise concurvity
concurvity(mod,full=F)

```
