---
title: Two dimensional smooths and spatial data
author: "Nick Giangreco"
output: html_document
---

```{r setup,message=F,warning=F}
knitr::opts_chunk$set(echo = TRUE,dpi = 400)
```

# Modelling soil pollution in the Nederlands

```{r}

library(mgcv)
data(meuse, package="sp")

# Inspect the data
head(meuse)
str(meuse)

# Fit the model
mod2d <- gam(cadmium ~ s(x,y), data = meuse, method = "REML")

# Inspect the model
summary(mod2d)
coef(mod2d)

```


# Adding more variables to predict soil pollution

```{r}

# Fit the model
mod2da <- gam(cadmium ~ s(x, y) + s(elev) + s(dist), 
              data = meuse, method = "REML")

# Inspect the model
summary(mod2da)

```

# Plotting the model surface

```{r}

mod2da <- gam(cadmium ~ s(x, y) + s(dist) + s(elev),
              data = meuse, method = "REML")

# Contour plot
plot(mod2da, pages = 1)

# 3D surface plot
plot(mod2da, scheme = 1, pages = 1)


# Colored heat map
plot(mod2da, scheme = 2, pages = 1)

```

# Customizing 3D plots

```{r}

mod2d <- gam(cadmium ~ s(x,y), data=meuse, method = "REML")

# Make the perspective plot with error surfaces
vis.gam(mod2d, view = c("x", "y"), 
        plot.type = "persp", se = 2)

# Rotate the same plot
vis.gam(mod2d, view = c("x", "y"),
        plot.type = "persp", se = 2, theta = 135)



```

# Extrapolation in surface plots

```{r}

mod2d <- gam(cadmium ~ s(x,y), data=meuse, method = "REML")

# Make plot with 5% extrapolation
vis.gam(mod2d, view = c("x", "y"), 
        plot.type = "contour", too.far=0.05)

# Overlay data
points(meuse)


# Make plot with 10% extrapolation
vis.gam(mod2d, view = c("x", "y"),
        plot.type = "contour", too.far = 0.1)

# Overlay data
points(meuse)

# Make plot with 25% extrapolation
vis.gam(mod2d, view = c("x", "y"),
        plot.type = "contour", too.far = 0.25)

# Overlay data
points(meuse)
```

# Soil pollution in different land uses

```{r}

# Fit a model with separate smooths for each land-use level
mod_sep <- gam(copper ~ s(dist, by = landuse) + landuse,
               data = meuse, method = "REML")

# Examine the summary
summary(mod_sep)


# Fit a model with factor-smooth interaction
mod_fs <- gam(copper ~ s(dist, landuse, bs = "fs"),
              data = meuse, method = "REML")

# Examine the summary
summary(mod_fs)

```

# Plotting pollution in different land uses

```{r}

mod_sep <- gam(copper ~ s(dist, by=landuse), data=meuse, method = "REML")
mod_fs <- gam(copper ~ s(dist, landuse, bs="fs"), data=meuse, method = "REML")

# Plot both the models with plot()
plot(mod_sep, pages = 1)
plot(mod_fs, pages = 1)


# Plot both the models with vis.gam()
vis.gam(mod_sep, view = c("dist", "landuse"), plot.type = "persp")
vis.gam(mod_fs, view = c("dist", "landuse"), plot.type = "persp")


```

# Polution models with multi-scale interactions

```{r}

# Fit the model
tensor_mod <- gam(cadmium ~ te(x, y, elev), 
                  data = meuse, method = "REML")

# Summarize and plot
summary(tensor_mod)
plot(tensor_mod)


# Fit the model
tensor_mod2 <- gam(cadmium ~ s(x, y) + s(elev) + ti(x, y, elev), 
                   data = meuse, method = "REML")

# Summarize and plot
summary(tensor_mod2)
plot(tensor_mod2, pages = 1)

```


